#!/bin/sh

mode=$1

if [ -z "$mode" ]; then
    mode="dev"
fi

if [ "$mode" = "dev" ]; then
    export APP_HOST="localhost"
    export APP_PORT="5001"
    export FLASK_ENV="development"
elif [ "$mode" = "prod" ]; then
    export APP_HOST="0.0.0.0"
    export APP_PORT="5002"
    export FLASK_ENV="production"
else
    echo "Unknown mode: '$mode'. Use one of the following modes: dev, prod"
    exit 1
fi

source venv/bin/activate

if [ "$?" -ne 0 ]; then
    echo "Execute './scripts/init-venv' first."
    exit 2
fi

cd src
echo "App running on host:'$APP_HOST' and port:'$APP_PORT'"
python app.py
