#!/bin/sh

mode=$1
env_location='src'

if [ -z "$mode" ]; then
    mode="dev"
fi

if [ ! -e "$env_location/.env" ]; then
    echo "No '$env_location/.env' file found."
    sh scripts/init-env "$env_location" "$mode"
    exit 2
fi
echo "'$env_location/.env' found."
source "$env_location/.env"

source venv/bin/activate
if [ "$?" -ne 0 ]; then
    echo "Execute './scripts/init-venv' first."
    exit 3
fi

cd src
echo "App running on host:'$APP_HOST' and port:'$APP_PORT'"
python app.py
