dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: echo "Run Unit Tests here."
    - name: "Integration Tests"
      script: echo "Run Integration Tests here."
    - stage: release
      name: "Release current repository as Docker Image."
      script: echo "Docker command."