dist: xenial

language: python
cache: pip

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      python:
        - "3.6"
        - "3.7"
      script:
        - echo "Run Unit Tests here."
        - pip list
    - name: "Integration Tests"
      python:
        - "3.6"
        - "3.7"
      script: echo "Run Integration Tests here."
        - pip list
    - stage: release
      name: "Release current repository as Docker Image."
      script:
        - echo "Docker command."
        - docker build -t bluefu/demo:latest .
        - docker images