version: '3.5'

volumes:
  db-vol: {}


services: 
  db:
    image: bluefu/mariadb-de:10
    env_file:
      ## File should contain:
      # MYSQL_ROOT_PASSWORD=password
      # MYSQL_USER=admin
      # MYSQL_PASSWORD=password
      # MYSQL_DATABASE=cm_db
      - ./docker/db/env/.env
    volumes:
      - db-vol:/var/lib/mysql
      ## File should contain:
      # [mysqld]
      # character-set-server=utf8mb4
      # collation-server=utf8mb4_unicode_ci
      # max_allowed_packet=500M
      - ./docker/db/conf/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    restart: always

  web-api:
    #image: bluefu/smartcoffee-web-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ## Look at ./docker/templates/.env.template for all environment variables
      ## Ignore 
      - ./docker/web-api/env/.env
      - ./docker/db/env/.env
    environment:
      ## These environment variables override the variables specified in ./docker/web-api/env/.env
      - DB_HOST=db
      # Intern port
      - APP_PORT=5000
      - FLASK_ENV=production
      - APP_PROCESSES=4
      - APP_THREADS=2
    ## For SSL support, mount your SSL cert.pem and privkey.pem files to the following locations
    #volumes:
    #  - ${CERT_FILE}:/ssl/cert.pem
    #  - ${PRIVKEYFILE}:/ssl/privkey.pem
    ports:
      - '60001:5000'
    restart: always

