version: '3.5'

volumes:
  dev-db: {}

services:
  mysql-dev:
    image: bluefu/mariadb-de:10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: cm_db
    ports:
      - "3308:3306"
    volumes:
      - dev-db:/var/lib/mysql
      - ./docker/db-conf.d/my.cnf:/etc/mysql/conf.d/config-file.cnf

  adminer:
    image: adminer
    ports:
      - 8081:8080
  
  # flask-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - MODE=dev
  #     # Should be empty in dev environment
  #     - CERT_FILE=
  #     # Should be empty in dev environment
  #     - KEY_FILE=
  #     # Customize as needed
  #     - DB_USER=admin
  #     - DB_PW=admin
  #     - DB_HOST=mysql-dev
  #     - DB_NAME=cm_db
  #     - DB_PORT=3306
  #     - APP_HOST=0.0.0.0
  #     - APP_PORT=5000
  #     - SECRET_KEY=XLrIjHvKsQskA7m
  #     - APP_URL_PREFIX=
  #     # Should be empty in dev environment
  #     - SWAGGER_BASE_URL=
  #     - FLASK_ENV=development
  #   ports:
  #     - 5001:5000



#  flask-dev:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-dev
#    links:
#      - mysql-dev
#    environment:
#      - APP_HOST=0.0.0.0
#      # Intern port of flask dev
#      - APP_PORT=5000
#      - DB_USER=bluefu
#      - DB_PW=ageofempires3
#      - DB_HOST=mysql-dev
#      - DB_NAME=bluefu_ttc
#      # Intern port of mysql DB
#      - DB_PORT=3306
#    ports:
#      - '5000:5000'