#!/bin/bash

uwsgi_file=$(ls -w 1 | grep -i *.ini)
uwsgi_name=$(echo ${uwsgi_file} | cut -d'.' -f 1)
pid_file=${uwsgi_name}.pid

if [[ -e "$pid_file" ]]; then
    echo "uWSGI Server is still running. Run 'uwsgi-stop'"
    exit 1
fi

source venv/bin/activate
uwsgi --ini ${uwsgi_file} &
