#!/bin/bash

uwsgi_file=$(ls -w 1 | grep -i *.ini)
uwsgi_name=$(echo ${uwsgi_file} | cut -d'.' -f 1)
pid_file=src/${uwsgi_name}.pid

if [[ -z "$pid_file" ]]; then
    	echo "No uWSGI Server is running. Execute 'uwsgi-start'"
	exit 1
fi

kill -SIGINT $(cat ${pid_file})
rm "$pid_file"
