type: object
properties:
  id:
    required: false
    type: integer
    description: ID des Kaffee-Profils
    example: 42
  name:
    required: true
    type: string
    description: Name des Kaffee-Profils
    example: Stark
  coffee_strength_in_percent:
    required: true
    type: integer
    minimum: 0
    maximum: 100
    description: Kaffeestärke in Prozent
    example: 66
  water_in_percent:
    required: true
    type: integer
    minimum: 1
    maximum: 100000
    description: 'water_in_percent' / 1000 = Wasseranteil in Prozent
    example: 66000
  user_id:
    required: true
    type: string
    description: Public ID des Nutzeraccounts, für den das Kaffee-Profil erstellt werden soll.
    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkMzg5MjRmYi05NDE3LTRhNTAtYjcxNS0wMWY4MDVjMjgwNjMiLCJleHAiOjE1NDI1NDE3NDV9.jbWsgjOFn6jEx0IGVoUaiqwt530_Fko8qgoMhGvl4mg  

