type: object
properties:
  name:
    required: true
    type: string
    description: Name des Kaffee-Profils
    example: Stark
  coffee_strength_in_percent:
    required: true
    type: integer
    minimum: 1
    maximum: 100
    description: Kaffeestärke in Prozent
    example: 66
  water_in_percent:
    required: true
    type: integer
    minimum: 1
    maximum: 100000
    description: 'water_in_percent' / 1000 = Wasseranteil in Prozent
    example: 66000