type: object
properties:
  name:
    required: true
    type: string
    description: Name des Kaffeeproduktes.
    example: Dallmayr Prodomo
  brand:
    required: true
    type: string
    description: Marke des Kaffeeproduktes.
    example: Dallmayr
  type:
    required: true
    type: string
    description: Typ des Kaffeeproduktes.
    example: Arabica