type: object
properties:
  id:
    required: true
    type: integer
    description: ID des Kaffeetyps
    example: 42
  name:
    required: true
    type: string
    description: Name des Kaffeetyps
    example: Arabica