type: object
properties:
  coffee_machine_id:
    required: true
    type: integer
    description: Die ID der Kaffeemaschine, welche den Auftrag ausgeführt hat.
    example: 42
  coffee_strength_in_percent:
    required: true
    type: integer
    minimum: 1
    maximum: 100000
    description: 'coffee_strength_in_percent' / 1000 = Kaffeestärke in Prozent
    example: 66000
  water_in_percent:
    required: true
    type: integer
    minimum: 1
    maximum: 100000
    description: 'water_in_percent' / 1000 = Wasseranteil in Prozent
    example: 66000
  price:
    required: true
    type: integer
    minimum: 0
    description: Der Preis pro Kaffee in Cents
    example: 10
  doses:
    required: true
    type: integer
    minimum: 1
    maximum: 2
    description: Die Anzahl der hergestellten Kaffee in diesem Auftrag
    example: 1
  coffee_product_id:
    required: true
    type: integer
    description: ID des Kaffeeproduktes, welches sich zum Zeitpunkt des Auftrags in der Kaffeemaschine befand.
  user_id:
    required: true
    type: string
    description: Public ID des Nutzeraccounts, für den der Job erstellt werden soll.
    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkMzg5MjRmYi05NDE3LTRhNTAtYjcxNS0wMWY4MDVjMjgwNjMiLCJleHAiOjE1NDI1NDE3NDV9.jbWsgjOFn6jEx0IGVoUaiqwt530_Fko8qgoMhGvl4mg