type: object
properties:
  id:
    required: true
    type: integer
    description: ID des Auftrags.
    example: 42
  create_date:
    required: true
    type: integer
    description: Erstellungsdatum des Auftrags.
  square_date:
    required: false
    type: integer
    description: Datum, an dem der Auftrag beglichen wurde.
  coffee_machine_id:
    required: true
    type: integer
    description: Die ID der Kaffeemaschine, welche den Auftrag ausgeführt hat.
    example: 42
  coffee_strength_in_percent:
    required: true
    type: integer
    minimum: 0
    maximum: 100
    description: Kaffeestärke in Prozent
    example: 66
  water_in_percent:
    required: true
    type: integer
    minimum: 0
    maximum: 100
    description: Wasseranteil in Prozent
    example: 66
  price:
    required: true
    type: integer
    minimum: 0
    description: Der Preis pro Kaffee in Cents
    example: 10
  doses:
    required: true
    type: integer
    minimum: 1
    maximum: 2
    description: Die Anzahl der hergestellten Kaffee in diesem Auftrag
    example: 1
  coffee_product_id:
    required: true
    type: integer
    description: ID des Kaffeeproduktes, welches sich zum Zeitpunkt des Auftrags in der Kaffeemaschine befand.
    example: 42
  user_id:
    required: true
    type: string
    description: Public ID des Nutzeraccounts, für den der Job erstellt werden soll.
    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkMzg5MjRmYi05NDE3LTRhNTAtYjcxNS0wMWY4MDVjMjgwNjMiLCJleHAiOjE1NDI1NDE3NDV9.jbWsgjOFn6jEx0IGVoUaiqwt530_Fko8qgoMhGvl4mg