type: object
properties:
  name:
    required: true
    type: string
    description: Neuer Username des Nutzeraccounts
  password:
    required: true
    type: string
    description: Neues Password des Nutzeraccounts
  email:
    required: true
    type: string
    description: Neue E-Mail-Adresse des Nutzeraccounts