type: object
properties:
  name:
    required: false
    type: string
    description: Neuer Username des Nutzeraccounts
    example: JohnDoe
  old_password:
    required: false
    type: string
    description: Altes Password des Nutzeraccounts
    example: oldpassword123
  new_password:
    required: false
    type: string
    description: Neues Password des Nutzeraccounts
    example: newpassword312
  email:
    required: false
    type: string
    description: Neue E-Mail-Adresse des Nutzeraccounts
    example: John.Doe@domain.tld