type: object
properties:
  public_id:
    type: string
    description: Öffentliche ID des Nutzeraccounts
    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkMzg5MjRmYi05NDE3LTRhNTAtYjcxNS0wMWY4MDVjMjgwNjMiLCJleHAiOjE1NDI1NDE3NDV9.jbWsgjOFn6jEx0IGVoUaiqwt530_Fko8qgoMhGvl4mg
  name:
    type: string
    description: Username des Nutzeraccounts
    example: Tom4421
  email:
    type: string
    description: E-Mail-Adresse des Nutzeraccounts
    example: some.email@gmx.de