type: object
properties:
  id:
    required: true
    type: integer
    description: ID des Kaffeeproduktes.
    example: 42
  name:
    required: true
    type: string
    description: Name des Kaffeeproduktes.
    example: Dallmayr Prodomo
  coffee_brand_id:
    required: true
    type: integer
    description: ID der Kaffeemarke.
    example: 42
  coffee_type_id:
    required: true
    type: integer
    description: ID des Kaffeetyps.
    example: 42