type: object
properties:
  name:
    required: true
    type: string
    description: Neuer Username des Nutzeraccounts
    example: John
  password:
    required: true
    type: string
    description: Neues Password des Nutzeraccounts
    example: somepassword
  email:
    required: true
    type: string
    description: Neue E-Mail-Adresse des Nutzeraccounts
    example: John.Doe@domain.tld